"""Shared machinery: briefs, the run log, the HTTP cache, git, the LLM wrapper."""

from __future__ import annotations

import json
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

from agents_work import netcache
from agents_work.brief import Brief, Source, slugify, table
from agents_work.gitsink import GitError, NotesRepo
from agents_work.llm import FakeLLM, LLM, LLMUnavailable, parse_json
from agents_work.netcache import Fetcher, Response
from agents_work.sources.news import Headline, News, _parse
from agents_work.sources.prices import PriceSource
from agents_work.store import Run, connect, recent, record, track


# -- brief -------------------------------------------------------------------

def test_brief_renders_frontmatter_title_and_footer():
    b = Brief(title="A brief", agent="research", target="NVDA", tags=["equity"])
    b.add("Snapshot", "body text").source("EDGAR", "https://sec.gov", "primary")
    text = b.render()
    assert text.startswith("---\n")
    assert "# A brief" in text
    assert "## Snapshot" in text
    assert "[EDGAR](https://sec.gov) — primary" in text
    assert "Generated by `research`" in text
    assert "degraded: false" in text


def test_degradations_appear_as_a_banner_and_a_flag():
    b = Brief(title="t", agent="a")
    b.degrade("no LLM").degrade("no LLM")          # deduplicated
    text = b.render()
    assert text.count("no LLM") == 1
    assert "> **Ran degraded.**" in text
    assert "degraded: true" in text


def test_empty_sections_are_dropped():
    b = Brief(title="t", agent="a")
    b.add("Empty", "   ").add("Full", "x")
    assert [s.heading for s in b.sections] == ["Full"]


def test_filename_is_dated_and_slugged():
    b = Brief(title="Anything", agent="a", target="NVDA Corp!",
              generated_at=datetime(2026, 8, 20, tzinfo=timezone.utc))
    assert b.filename == "2026-08-20-nvda-corp.md"


@pytest.mark.parametrize("raw,expected", [
    ("NVDA", "nvda"), ("Market open — 2026", "market-open-2026"),
    ("...", "untitled"), ("A  B", "a-b"),
])
def test_slugify(raw, expected):
    assert slugify(raw) == expected


def test_yaml_scalars_are_quoted_when_they_have_to_be():
    b = Brief(title="Has: a colon", agent="a", target="x")
    b.extra_meta["note"] = "line\nbreak"
    fm = b.frontmatter()
    assert 'title: "Has: a colon"' in fm
    assert 'note: "line break"' in fm


def test_table_renders_and_admits_emptiness():
    assert table(["A", "B"], [[1, 2]]) == "| A | B |\n| --- | --- |\n| 1 | 2 |"
    assert table(["A"], []) == "_No data._"
    assert "|  |" in table(["A", "B"], [[None, ""]])


def test_write_creates_the_directory(tmp_path):
    b = Brief(title="t", agent="a", target="x")
    path = b.write(tmp_path / "nested" / "deeper")
    assert path.is_file() and path.read_text() == b.render()


def test_duplicate_sources_are_not_repeated():
    b = Brief(title="t", agent="a")
    b.source("X", "u").source("X", "u").source("X", "v")
    assert len(b.sources) == 2


# -- run log -----------------------------------------------------------------

def test_record_and_recent_round_trip(tmp_path):
    conn = connect(tmp_path / "runs.db")
    record(conn, Run(agent="research", target="NVDA", ok=True, summary="fine",
                     degradations=["no LLM"]))
    record(conn, Run(agent="scout", target="boards", ok=False, error="boom"))
    rows = recent(conn)
    assert [r["agent"] for r in rows] == ["scout", "research"]
    assert rows[1]["degradations"] == ["no LLM"]
    assert rows[0]["ok"] is False
    assert recent(conn, agent="research")[0]["target"] == "NVDA"


def test_track_logs_a_failure_and_reraises(tmp_path):
    conn = connect(tmp_path / "runs.db")
    with pytest.raises(ValueError):
        with track(conn, "research", "NVDA"):
            raise ValueError("nope")
    row = recent(conn)[0]
    assert row["ok"] is False
    assert "ValueError: nope" in row["error"]
    assert row["duration_s"] >= 0


def test_track_logs_success(tmp_path):
    conn = connect(tmp_path / "runs.db")
    with track(conn, "briefing") as run:
        run.summary = "done"
    row = recent(conn)[0]
    assert row["ok"] is True and row["summary"] == "done"


# -- http cache --------------------------------------------------------------

class FakeClient:
    def __init__(self, status=200, text="hello", calls=None, boom=False):
        self.status, self.text, self.calls, self.boom = status, text, calls, boom

    def __enter__(self):
        return self

    def __exit__(self, *a):
        return False

    def get(self, url, headers=None):
        return self._respond("GET", url, None)

    def post(self, url, headers=None, json=None):
        return self._respond("POST", url, json)

    def _respond(self, verb, url, body):
        if self.calls is not None:
            self.calls.append(url if body is None else (verb, url, body))
        if self.boom:
            raise netcache.httpx.ConnectError("down")
        return type("R", (), {"status_code": self.status, "text": self.text})()


def test_fetch_caches_and_reuses(tmp_path, monkeypatch):
    calls = []
    monkeypatch.setattr(netcache.httpx, "Client",
                        lambda **kw: FakeClient(calls=calls))
    f = Fetcher(tmp_path / "cache", ttl=900)
    first = f.fetch("https://example.com/a")
    second = f.fetch("https://example.com/a")
    assert first.ok and second.from_cache
    assert len(calls) == 1
    assert f.stats == {"hit": 1, "miss": 1, "error": 0}


def test_expired_cache_is_refetched(tmp_path, monkeypatch):
    calls = []
    monkeypatch.setattr(netcache.httpx, "Client", lambda **kw: FakeClient(calls=calls))
    f = Fetcher(tmp_path / "cache", ttl=0)
    f.fetch("https://example.com/a")
    f.fetch("https://example.com/a")
    assert len(calls) == 2


def test_a_network_failure_serves_stale_cache(tmp_path, monkeypatch):
    monkeypatch.setattr(netcache.httpx, "Client", lambda **kw: FakeClient(text="fresh"))
    f = Fetcher(tmp_path / "cache", ttl=900)
    f.fetch("https://example.com/a")
    monkeypatch.setattr(netcache.httpx, "Client", lambda **kw: FakeClient(boom=True))
    stale = Fetcher(tmp_path / "cache", ttl=0)
    got = stale.fetch("https://example.com/a")
    assert got is not None and got.text == "fresh" and got.from_cache


def test_a_network_failure_without_cache_returns_none(tmp_path, monkeypatch):
    monkeypatch.setattr(netcache.httpx, "Client", lambda **kw: FakeClient(boom=True))
    assert Fetcher(tmp_path / "cache").fetch("https://example.com/gone") is None


def test_offline_mode_never_calls_out(tmp_path, monkeypatch):
    monkeypatch.setattr(netcache.httpx, "Client", lambda **kw: FakeClient(text="live"))
    Fetcher(tmp_path / "cache", ttl=900).fetch("https://example.com/a")

    def explode(**kw):
        raise AssertionError("offline fetcher went to the network")

    monkeypatch.setattr(netcache.httpx, "Client", explode)
    offline = Fetcher(tmp_path / "cache", ttl=0, offline=True)
    assert offline.fetch("https://example.com/a").text == "live"
    assert offline.fetch("https://example.com/never-seen") is None


def test_error_responses_are_not_cached(tmp_path, monkeypatch):
    calls = []
    monkeypatch.setattr(netcache.httpx, "Client",
                        lambda **kw: FakeClient(status=404, calls=calls))
    f = Fetcher(tmp_path / "cache", ttl=900)
    f.fetch("https://example.com/missing")
    f.fetch("https://example.com/missing")
    assert len(calls) == 2


def test_response_json_survives_a_non_json_body():
    assert Response("u", 200, "<html>").json({"fallback": 1}) == {"fallback": 1}


def test_params_are_merged_into_the_cache_key(tmp_path, monkeypatch):
    calls = []
    monkeypatch.setattr(netcache.httpx, "Client", lambda **kw: FakeClient(calls=calls))
    f = Fetcher(tmp_path / "cache", ttl=900)
    f.fetch("https://example.com/a", params={"q": "1"})
    f.fetch("https://example.com/a", params={"q": "2"})
    assert len(calls) == 2


def test_a_body_turns_the_fetch_into_a_post(tmp_path, monkeypatch):
    """Workday and Oracle publish their boards behind POST-only JSON endpoints.
    They go through the same cache-first fetcher as everything else rather than
    each growing a client that skips the throttle and the stale fallback."""
    calls = []
    monkeypatch.setattr(netcache.httpx, "Client", lambda **kw: FakeClient(calls=calls))
    f = Fetcher(tmp_path / "cache", ttl=900)
    r = f.fetch("https://x.wd1.myworkdayjobs.com/wday/cxs/x/C/jobs", body={"offset": 0})
    assert r.ok
    assert calls == [("POST", "https://x.wd1.myworkdayjobs.com/wday/cxs/x/C/jobs",
                      {"offset": 0})]


def test_the_request_body_is_part_of_the_cache_key(tmp_path, monkeypatch):
    """Two pages of a Workday board differ only by the `offset` in their
    payload; a key that ignored it would serve page 1 for every page."""
    calls = []
    monkeypatch.setattr(netcache.httpx, "Client", lambda **kw: FakeClient(calls=calls))
    f = Fetcher(tmp_path / "cache", ttl=900)
    url = "https://x.wd1.myworkdayjobs.com/wday/cxs/x/C/jobs"
    f.fetch(url, body={"offset": 0})
    f.fetch(url, body={"offset": 20})
    assert len(calls) == 2
    assert f.fetch(url, body={"offset": 0}).from_cache


def test_workday_and_oracle_hosts_get_a_courtesy_rate_limit():
    """They are named per tenant, so they can never be listed one by one."""
    assert netcache._rate_for("nvidia.wd5.myworkdayjobs.com") > netcache._DEFAULT_RATE
    assert netcache._rate_for("hdow.fa.us6.oraclecloud.com") > netcache._DEFAULT_RATE
    assert netcache._rate_for("www.sec.gov") == netcache._RATE_LIMITS["www.sec.gov"]


def test_rate_limiter_spaces_calls_to_the_same_host():
    netcache._last_call.clear()
    t0 = time.monotonic()
    netcache._throttle("www.sec.gov")
    netcache._throttle("www.sec.gov")
    assert time.monotonic() - t0 >= 0.10


# -- cache prune -------------------------------------------------------------

def _entry(cache: Path, name: str, size: int, age_s: float) -> Path:
    cache.mkdir(parents=True, exist_ok=True)
    f = cache / name
    f.write_text("x" * size)
    import os
    stamp = time.time() - age_s
    os.utime(f, (stamp, stamp))
    return f


def test_prune_is_a_noop_under_the_cap(tmp_path):
    cache = tmp_path / "cache"
    _entry(cache, "a.json", 100, 10)
    st = netcache.prune_cache(cache, 10_000)
    assert st["removed"] == 0 and st["kept"] == 1
    assert (cache / "a.json").exists()


def test_prune_evicts_oldest_first_until_it_fits(tmp_path):
    cache = tmp_path / "cache"
    _entry(cache, "new.json", 400, age_s=1)
    _entry(cache, "mid.json", 400, age_s=100)
    _entry(cache, "old.json", 400, age_s=10_000)
    st = netcache.prune_cache(cache, 900)
    # 400 + 400 fits under 900; the third does not, and it is the stale one.
    assert st["kept"] == 2 and st["removed"] == 1
    assert (cache / "new.json").exists() and (cache / "mid.json").exists()
    assert not (cache / "old.json").exists()
    assert st["freed_bytes"] == 400


def test_prune_keeps_the_big_recent_blob_over_small_stale_ones(tmp_path):
    """The case this exists for: one 12MB companyfacts pull from a ticker nobody
    researches again should go before anything the nightly sweep still reads."""
    cache = tmp_path / "cache"
    _entry(cache, "stale_big.json", 5_000, age_s=90_000)
    for i in range(5):
        _entry(cache, f"nightly{i}.json", 200, age_s=60)
    st = netcache.prune_cache(cache, 1_500)
    assert not (cache / "stale_big.json").exists()
    assert all((cache / f"nightly{i}.json").exists() for i in range(5))
    assert st["kept"] == 5 and st["kept_bytes"] == 1_000


def test_prune_dry_run_reports_without_deleting(tmp_path):
    cache = tmp_path / "cache"
    _entry(cache, "old.json", 400, age_s=10_000)
    _entry(cache, "new.json", 400, age_s=1)
    st = netcache.prune_cache(cache, 500, dry_run=True)
    assert st["removed"] == 1 and st["freed_bytes"] == 400
    assert (cache / "old.json").exists() and (cache / "new.json").exists()


def test_prune_collects_stray_tmp_files_but_spares_fresh_ones(tmp_path):
    """A .tmp is a write that died between write_text and replace. An old one is
    garbage; a fresh one may belong to a fetch running right now."""
    cache = tmp_path / "cache"
    _entry(cache, "dead.tmp", 50, age_s=netcache.CACHE_TMP_MAX_AGE + 60)
    _entry(cache, "live.tmp", 50, age_s=5)
    st = netcache.prune_cache(cache, 10_000)
    assert st["tmp_removed"] == 1
    assert not (cache / "dead.tmp").exists() and (cache / "live.tmp").exists()


def test_prune_ignores_tmp_files_when_budgeting(tmp_path):
    cache = tmp_path / "cache"
    _entry(cache, "keep.json", 400, age_s=1)
    _entry(cache, "live.tmp", 5_000, age_s=5)
    st = netcache.prune_cache(cache, 500)
    assert st["kept"] == 1 and st["removed"] == 0
    assert (cache / "keep.json").exists()


def test_prune_survives_a_missing_directory(tmp_path):
    st = netcache.prune_cache(tmp_path / "never-created", 1_000)
    assert st == {"kept": 0, "kept_bytes": 0, "removed": 0, "freed_bytes": 0,
                  "tmp_removed": 0}


def test_prune_keeps_a_live_cache_readable(tmp_path, monkeypatch):
    """End to end: a pruned-away entry re-fetches, a kept one still serves."""
    monkeypatch.setattr(netcache.httpx, "Client", lambda **kw: FakeClient(text="live"))
    f = Fetcher(tmp_path / "cache", ttl=900)
    f.fetch("https://example.com/keep")
    assert f.fetch("https://example.com/keep").from_cache
    netcache.prune_cache(tmp_path / "cache", 0)          # evict everything
    assert not f.fetch("https://example.com/keep").from_cache


# -- git ---------------------------------------------------------------------

def test_repo_is_created_idempotently(tmp_path):
    repo = NotesRepo(tmp_path / "notes")
    repo.ensure()
    repo.ensure()
    assert (tmp_path / "notes" / ".git").is_dir()
    assert (tmp_path / "notes" / "README.md").is_file()


def test_commit_file_writes_stages_and_commits(tmp_path):
    repo = NotesRepo(tmp_path / "notes")
    result = repo.commit_file("briefs/a.md", "hello", "add a")
    assert result.committed and result.sha
    assert (tmp_path / "notes" / "briefs" / "a.md").read_text() == "hello"
    assert repo.log()[0]["subject"] == "add a"


def test_changed_content_commits_again(tmp_path):
    repo = NotesRepo(tmp_path / "notes")
    repo.commit_file("briefs/a.md", "one", "first")
    second = repo.commit_file("briefs/a.md", "two", "second")
    assert second.committed
    assert len(repo.log()) == 3          # init + two


def test_a_dead_remote_keeps_the_commit_local(tmp_path):
    repo = NotesRepo(tmp_path / "notes", remote="file:///nonexistent/remote.git")
    result = repo.commit_file("briefs/a.md", "hello", "add a")
    assert result.committed
    assert not result.pushed
    assert result.push_error


def test_log_of_a_missing_repo_is_empty(tmp_path):
    assert NotesRepo(tmp_path / "nope").log() == []


def test_git_errors_are_typed(tmp_path):
    (tmp_path / "notes").mkdir()
    with pytest.raises(GitError):
        NotesRepo(tmp_path / "notes")._commit("nothing staged")


# -- llm ---------------------------------------------------------------------

def test_llm_without_a_key_is_unavailable(cfg):
    llm = LLM(cfg)
    assert not llm.available
    with pytest.raises(LLMUnavailable, match="no AGENTS_LLM_API_KEY"):
        llm.complete("hi")


@pytest.mark.parametrize("raw,expected", [
    ('{"a": 1}', {"a": 1}),
    ('```json\n{"a": 1}\n```', {"a": 1}),
    ('Sure!\n```\n[{"b": 2}]\n```\nHope that helps', [{"b": 2}]),
    ('Here: {"a": 1} — done', {"a": 1}),
])
def test_parse_json_digs_through_model_prose(raw, expected):
    assert parse_json(raw, default=None) == expected


def test_parse_json_gives_up_gracefully():
    assert parse_json("no json at all", default="fallback") == "fallback"


def test_fake_llm_records_prompts_and_replays_responses(cfg):
    llm = FakeLLM(cfg, ["first", "second"])
    assert llm.complete("a") == "first"
    assert llm.complete("b") == "second"
    assert llm.complete("c") == "FAKE"
    assert llm.prompts == ["a", "b", "c"]


def test_fake_llm_can_raise(cfg):
    llm = FakeLLM(cfg, [LLMUnavailable("down")])
    with pytest.raises(LLMUnavailable):
        llm.complete("a")


def test_llm_json_falls_back_when_unavailable(cfg):
    assert FakeLLM(cfg, available=False).json("prompt", default=[]) == []


# -- lake staleness ----------------------------------------------------------

def test_coverage_gap_counts_to_today_when_no_end_given():
    from agents_work.sources.prices import coverage_gap_days
    gap = coverage_gap_days("2026-07-06", None, today="2026-08-21")
    assert gap == 46


def test_coverage_gap_respects_an_explicit_end():
    """A backtest that asked for 2020 is not stale because it is 2026."""
    from agents_work.sources.prices import coverage_gap_days
    assert coverage_gap_days("2020-12-31", "2020-12-31", today="2026-08-21") == 0
    assert coverage_gap_days("2020-11-30", "2020-12-31", today="2026-08-21") == 31


def test_coverage_gap_never_looks_past_today():
    from agents_work.sources.prices import coverage_gap_days
    assert coverage_gap_days("2026-08-21", "2027-01-01", today="2026-08-21") == 0


def test_a_stale_lake_is_reported_not_returned_silently(tmp_path, lake):
    """The regression this exists for: a lake with years of history that stopped
    updating returns every row it ever had, so no row-count check can catch it.
    The run must say the window is short, not just quietly end early."""
    from agents_work.sources.prices import PriceSource
    ps = PriceSource(lake, allow_network=False)
    hist = ps.history("SPY", start="2015-01-01")
    assert not hist.empty
    assert any("ends" in n and "short by" in n for n in ps.notes), ps.notes


def test_a_window_the_lake_covers_raises_no_note(lake):
    from agents_work.sources.prices import PriceSource
    ps = PriceSource(lake, allow_network=False)
    last = ps.history("SPY", min_rows=2).index[-1].date()
    ps.notes.clear()
    ps.history("SPY", start="2020-01-01", end=str(last))
    assert ps.notes == []


# -- news --------------------------------------------------------------------

def _rss(*items):
    body = "".join(
        f"<item><title>{t}</title><link>{u}</link><source>{s}</source>"
        f"<pubDate>{d}</pubDate></item>" for t, u, s, d in items)
    return f'<?xml version="1.0"?><rss><channel>{body}</channel></rss>'


def _stamp(hours_ago):
    return (datetime.now(timezone.utc) - timedelta(hours=hours_ago)).strftime(
        "%a, %d %b %Y %H:%M:%S GMT")


def test_news_parses_and_unescapes():
    items = _parse(_rss(("Chips &amp; margins", "https://e/1", "Wire", _stamp(2))))
    assert items[0].title == "Chips & margins"
    assert items[0].source == "Wire"


def test_news_filters_by_age():
    xml = _rss(("new", "https://e/1", "Wire", _stamp(2)),
               ("old", "https://e/2", "Wire", _stamp(500)))
    assert [h.title for h in _parse(xml, max_age_hours=24)] == ["new"]


def test_news_respects_the_limit():
    xml = _rss(*[(f"t{i}", f"https://e/{i}", "Wire", _stamp(1)) for i in range(10)])
    assert len(_parse(xml, limit=3)) == 3


def test_malformed_rss_is_survivable():
    assert _parse("<rss><channel><item>") == []


def test_items_without_a_title_are_skipped():
    assert _parse('<rss><channel><item><link>https://e/1</link></item></channel></rss>') == []


@pytest.mark.parametrize("hours,expected", [(0.25, "15m ago"), (5, "5h ago"), (72, "3d ago")])
def test_headline_age_reads_naturally(hours, expected):
    h = Headline("t", "u", "s", datetime.now(timezone.utc) - timedelta(hours=hours))
    assert h.when == expected


def test_undated_headline_says_so():
    assert Headline("t", "u", "s", None).when == "undated"


def test_news_search_returns_empty_when_the_feed_is_down(fetcher):
    assert News(fetcher).search("anything") == []


# -- prices ------------------------------------------------------------------

def test_history_reads_the_lake(lake):
    df = PriceSource(lake, allow_network=False).history("SPY")
    assert len(df) == 800
    assert list(df.columns) == ["open", "high", "low", "close", "adj_close", "volume"]
    assert df.index.is_monotonic_increasing


def test_history_slices_by_date(lake):
    df = PriceSource(lake, allow_network=False).history("SPY", start="2021-01-01",
                                                        end="2021-12-31", min_rows=1)
    assert df.index.min().year == 2021 and df.index.max().year == 2021


def test_unknown_symbol_returns_an_empty_frame_with_a_note(lake):
    src = PriceSource(lake, allow_network=False)
    df = src.history("NOSUCH")
    assert df.empty and list(df.columns) == ["open", "high", "low", "close",
                                             "adj_close", "volume"]
    assert any("no price history" in n for n in src.notes)


def test_a_corrupt_shard_is_reported_not_fatal(lake):
    (lake / "symbol=BAD").mkdir()
    (lake / "symbol=BAD" / "BAD.parquet").write_text("not parquet")
    src = PriceSource(lake, allow_network=False)
    assert src.history("BAD").empty
    assert any("unreadable" in n for n in src.notes)


def test_quotes_fall_back_to_stored_closes(lake):
    q = PriceSource(lake, allow_network=False).quotes(["SPY"])[0]
    assert q.ok and q.change_pct is not None
    assert "stale" in q.as_of


def test_quote_change_pct_needs_both_sides():
    from agents_work.sources.prices import Quote
    assert Quote("X", last=10, prev_close=None).change_pct is None
    assert Quote("X", last=11, prev_close=10).change_pct == pytest.approx(10.0)
