"""The one-page document every agent emits.

A brief is data first and prose second: sections are assembled from real
fetched facts, and the LLM only ever writes *into* a section. That ordering is
deliberate — it means an LLM outage costs you the analysis paragraphs, not the
document, and the reader can always see which sources fed it.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s or "untitled"


def _yaml_scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    if s == "" or re.search(r"[:#\[\]{}\n\"']", s) or s.strip() != s:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'
    return s


@dataclass
class Source:
    label: str
    url: str = ""
    note: str = ""

    def render(self) -> str:
        bits = f"[{self.label}]({self.url})" if self.url else self.label
        return f"- {bits}" + (f" — {self.note}" if self.note else "")


@dataclass
class Section:
    heading: str
    body: str
    level: int = 2

    def render(self) -> str:
        return f"{'#' * self.level} {self.heading}\n\n{self.body.strip()}\n"


@dataclass
class Brief:
    title: str
    agent: str
    target: str = ""
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    sections: list[Section] = field(default_factory=list)
    sources: list[Source] = field(default_factory=list)
    degradations: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    extra_meta: dict = field(default_factory=dict)

    def add(self, heading: str, body: str, level: int = 2) -> "Brief":
        if body and body.strip():
            self.sections.append(Section(heading, body, level))
        return self

    def source(self, label: str, url: str = "", note: str = "") -> "Brief":
        if not any(s.label == label and s.url == url for s in self.sources):
            self.sources.append(Source(label, url, note))
        return self

    def degrade(self, msg: str) -> "Brief":
        if msg and msg not in self.degradations:
            self.degradations.append(msg)
        return self

    @property
    def date(self) -> str:
        return self.generated_at.strftime("%Y-%m-%d")

    @property
    def filename(self) -> str:
        stem = slugify(self.target or self.title)
        return f"{self.date}-{stem}.md"

    def frontmatter(self) -> str:
        meta = {
            "title": self.title,
            "agent": self.agent,
            "target": self.target,
            "date": self.date,
            "generated_at": self.generated_at.isoformat(timespec="seconds"),
            **self.extra_meta,
        }
        lines = ["---"]
        for k, v in meta.items():
            lines.append(f"{k}: {_yaml_scalar(v)}")
        if self.tags:
            lines.append("tags: [" + ", ".join(_yaml_scalar(t) for t in self.tags) + "]")
        lines.append("degraded: " + ("true" if self.degradations else "false"))
        lines.append("---")
        return "\n".join(lines)

    def render(self) -> str:
        parts = [self.frontmatter(), "", f"# {self.title}", ""]
        if self.degradations:
            parts.append("> **Ran degraded.** " + " · ".join(self.degradations) + "\n")
        parts += [s.render() for s in self.sections]
        if self.sources:
            parts.append("## Sources\n\n" + "\n".join(s.render() for s in self.sources) + "\n")
        parts.append(
            f"---\n*Generated by `{self.agent}` at "
            f"{self.generated_at.strftime('%Y-%m-%d %H:%M UTC')}. "
            "Data assembled programmatically; analysis is model-written and unverified.*\n"
        )
        return "\n".join(parts)

    def write(self, directory: Path) -> Path:
        directory = Path(directory)
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / self.filename
        path.write_text(self.render())
        return path


def table(headers: list[str], rows: list[list], *, align: list[str] | None = None) -> str:
    """Markdown table. Empty rows render as an honest 'no data' line."""
    if not rows:
        return "_No data._"
    align = align or ["---"] * len(headers)
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join(align) + " |"]
    for r in rows:
        out.append("| " + " | ".join("" if c is None else str(c) for c in r) + " |")
    return "\n".join(out)
